## NumPY
1. Numeric Python
2. Numpy array alternative to python list
3. Fast and easy
4. contain only single type

In [2]:
import numpy as np

In [3]:
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])

In [4]:
bmi = np_weight/np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [6]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [7]:
bmi[1]

20.97505668934241

In [8]:
bmi > 23

array([False, False, False,  True, False])

In [9]:
bmi[bmi > 23]

array([24.7473475])

## 2d array

In [11]:
np_2d = np.array([
    [1.73,1.68,1.71,1.89,1.79],
    [65.4,59.2,63.6,88.4,68.7]
])

In [12]:
np_2d.shape

(2, 5)

In [13]:
np_2d[0][2]

1.71

In [14]:
np_2d[0,2]

1.71

In [15]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [16]:
np_2d[1]

array([65.4, 59.2, 63.6, 88.4, 68.7])

## Numpy basic statiscs

In [18]:
height = np.round(np.random.normal(1.75,0.20,5000),2)
weight = np.round(np.random.normal(60.32,15,5000),2)

In [20]:
np_city = np.column_stack((height,weight))
np_city

array([[ 1.54, 74.81],
       [ 1.54, 62.03],
       [ 2.06, 56.3 ],
       ...,
       [ 1.86, 78.88],
       [ 1.79, 66.58],
       [ 1.97, 46.05]])

In [21]:
np.mean(np_city[:,0])

1.750694

In [22]:
np.median(np_city[:,0])

1.75

In [23]:
np.corrcoef(np_city[:,0],np_city[:,1])

array([[1.        , 0.00791721],
       [0.00791721, 1.        ]])

In [24]:
np.std(np_city[:,0])

0.1993500899523248